version: '3.8'

services:
  backend:
    build: ./backend
    container_name: hidden_gems_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/hiddengems
      - JWT_SECRET=prod_super_secure_jwt_secret_key_100
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: hidden_gems_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:6.0
    container_name: hidden_gems_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
